export const theme = {
  colors: {
    primary: "#1a1a1a",
    accent: "#8b5cf6",
    border: "#e5e7eb",
    backgroundLight: "#f3f4f6",
    textDark: "#111827",
    textMuted: "#9ca3af",
    error: "#ef4444",
    outOfStock: "#6b7280",
    warning: "#f59e0b",
    success: "#10b981",
  },
  shadows: {
    card: "0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
  },
  buttons: {
    primary: {
      backgroundColor: "#1a1a1a",
      color: "#ffffff",
      border: "none",
      borderRadius: "6px",
      cursor: "pointer",
      fontWeight: "600",
      transition: "background-color 0.2s",
      outline: "none",
    },
    secondary: {
      backgroundColor: "#ffffff",
      color: "#1a1a1a",
      border: "1px solid #1a1a1a",
      borderRadius: "6px",
      cursor: "pointer",
      fontWeight: "600",
      transition: "all 0.2s",
      outline: "none",
    },
    smallPrimary: {
      backgroundColor: "#1a1a1a",
      color: "#ffffff",
      border: "none",
      borderRadius: "6px",
      cursor: "pointer",
      fontWeight: "600",
      fontSize: "0.85rem",
      padding: "0.5rem 0.85rem",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      transition: "all 0.2s ease",
      outline: "none",
    },
    smallSecondary: {
      backgroundColor: "#ffffff",
      color: "#1a1a1a",
      border: "1px solid #1a1a1a",
      borderRadius: "6px",
      cursor: "pointer",
      fontWeight: "600",
      fontSize: "0.85rem",
      padding: "0.5rem 0.85rem",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      transition: "all 0.2s ease",
      outline: "none",
    },
    qty: {
      width: "28px",
      height: "28px",
      borderRadius: "50%",
      border: "none",
      backgroundColor: "#ffffff",
      color: "#1a1a1a",
      fontSize: "1.1rem",
      fontWeight: "bold",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "pointer",
      boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
      transition: "all 0.15s ease",
      outline: "none",
    },
    qtyDisabled: {
      width: "28px",
      height: "28px",
      borderRadius: "50%",
      border: "none",
      backgroundColor: "transparent",
      color: "#9ca3af",
      fontSize: "1.1rem",
      fontWeight: "bold",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "not-allowed",
      outline: "none",
      opacity: 0.5,
    },
    disabled: {
      backgroundColor: "#e5e7eb",
      color: "#9ca3af",
      cursor: "not-allowed",
      border: "none",
      opacity: 0.6,
    },
  },
  inputs: {
    text: {
      padding: "0.6rem 1rem",
      borderRadius: "8px",
      border: "1px solid #d1d5db",
      backgroundColor: "#ffffff",
      fontSize: "0.9rem",
      color: "#1f2937",
      outline: "none",
      transition: "border-color 0.2s",
      boxSizing: "border-box",
    },
  },
  layouts: {
    page: {
      padding: "2rem 3rem",
      fontFamily: "system-ui, sans-serif",
    },
    card: {
      border: "1px solid #e5e7eb",
      padding: "1rem",
      borderRadius: "8px",
      overflow: "hidden",
      display: "flex",
      flexDirection: "column",
      boxShadow: "0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
      backgroundColor: "#ffffff",
    },
  },
  empty: {
    textAlign: "center",
    padding: "4rem",
    color: "#111827",
  },
};
