export const theme = {
  colors: {
    primary: "var(--color-primary)",
    accent: "var(--color-accent)",
    border: "var(--color-border)",
    backgroundLight: "var(--color-background-light)",
    textDark: "var(--color-text-dark)",
    textMuted: "var(--color-text-muted)",
    error: "var(--color-error)",
    outOfStock: "var(--color-out-of-stock)",
    warning: "var(--color-warning)",
    success: "var(--color-success)",
    errorLight: "var(--danger-bg)",
    overlayBg: "rgba(0, 0, 0, 0.4)",
    navbarHighlight: "rgba(255, 255, 255, 0.15)",
  },
  shadows: {
    card: "var(--shadow-card)",
  },
  buttons: {
    primary: {
      backgroundColor: "var(--button-primary-bg)",
      color: "var(--button-primary-color)",
      border: "none",
      borderRadius: "6px",
      cursor: "pointer",
      fontWeight: "600",
      transition: "background-color 0.2s",
      outline: "none",
    },
    secondary: {
      backgroundColor: "var(--button-secondary-bg)",
      color: "var(--button-secondary-color)",
      border: "1px solid var(--button-secondary-border)",
      borderRadius: "6px",
      cursor: "pointer",
      fontWeight: "600",
      transition: "all 0.2s",
      outline: "none",
    },
    smallPrimary: {
      backgroundColor: "var(--button-primary-bg)",
      color: "var(--button-primary-color)",
      border: "none",
      borderRadius: "6px",
      cursor: "pointer",
      fontWeight: "600",
      fontSize: "0.85rem",
      padding: "0.5rem 0.85rem",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      transition: "all 0.2s ease",
      outline: "none",
    },
    smallSecondary: {
      backgroundColor: "var(--button-secondary-bg)",
      color: "var(--button-secondary-color)",
      border: "1px solid var(--button-secondary-border)",
      borderRadius: "6px",
      cursor: "pointer",
      fontWeight: "600",
      fontSize: "0.85rem",
      padding: "0.5rem 0.85rem",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      transition: "all 0.2s ease",
      outline: "none",
    },
    qty: {
      width: "28px",
      height: "28px",
      borderRadius: "50%",
      border: "none",
      backgroundColor: "var(--button-qty-bg)",
      color: "var(--button-qty-color)",
      fontSize: "1.1rem",
      fontWeight: "bold",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "pointer",
      boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
      transition: "all 0.15s ease",
      outline: "none",
    },
    qtyDisabled: {
      width: "28px",
      height: "28px",
      borderRadius: "50%",
      border: "none",
      backgroundColor: "transparent",
      color: "var(--button-disabled-color)",
      fontSize: "1.1rem",
      fontWeight: "bold",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "not-allowed",
      outline: "none",
      opacity: 0.5,
    },
    disabled: {
      backgroundColor: "var(--button-disabled-bg)",
      color: "var(--button-disabled-color)",
      cursor: "not-allowed",
      border: "none",
      opacity: 0.6,
    },
  },
  inputs: {
    text: {
      padding: "0.6rem 1rem",
      borderRadius: "8px",
      border: "1px solid var(--color-border)",
      backgroundColor: "var(--color-card-bg)",
      fontSize: "0.9rem",
      color: "var(--color-text-dark)",
      outline: "none",
      transition: "border-color 0.2s",
      boxSizing: "border-box",
    },
  },
  layouts: {
    page: {
      padding: "2rem 3rem",
      fontFamily: "system-ui, sans-serif",
    },
    card: {
      border: "1px solid var(--color-border)",
      padding: "1rem",
      borderRadius: "8px",
      overflow: "hidden",
      display: "flex",
      flexDirection: "column",
      boxShadow: "var(--shadow-card)",
      backgroundColor: "var(--color-card-bg)",
    },
  },
  empty: {
    textAlign: "center",
    padding: "4rem",
    color: "var(--color-text-dark)",
  },
};
