const reviewsByProductId = {
  // ── Electronics ──────────────────────────────────────────
  e1: [
    {
      id: "e1-r1",
      name: "Alex M.",
      rating: 5,
      title: "Best noise cancellation at this price",
      body: "I commute on the subway daily and these headphones completely block out the noise. The 30-hour battery is no joke either — I charge them once a week at most. Comfortable enough to wear for hours without fatigue.",
      date: "Mar 12, 2025",
    },
    {
      id: "e1-r2",
      name: "Priya S.",
      rating: 4,
      title: "Great sound, slightly tight fit",
      body: "Sound quality is excellent for the price — rich bass and clear mids. My only gripe is they clamp a bit tight on larger heads. After a week of use they loosened up, but the first few days were uncomfortable.",
      date: "Feb 28, 2025",
    },
    {
      id: "e1-r3",
      name: "Jordan K.",
      rating: 5,
      title: "Replaced my $300 pair with these",
      body: "I was skeptical but these genuinely rival headphones twice the price. The folding design is great for travel and the Bluetooth connection is rock solid. Haven't had a single dropout in two months of daily use.",
      date: "Jan 15, 2025",
    },
    {
      id: "e1-r4",
      name: "Sam T.",
      rating: 4,
      title: "Solid everyday headphones",
      body: "They do everything well without being exceptional at any one thing. ANC works great on planes and trains. Wish the app had more EQ options but out of the box they sound balanced and natural.",
      date: "Dec 5, 2024",
    },
  ],

  e2: [
    {
      id: "e2-r1",
      name: "Marcus L.",
      rating: 5,
      title: "The tactile switches are perfect",
      body: "Coming from a membrane keyboard, the difference is night and day. The tactile bump is satisfying without being too loud for an office environment. RGB customization is deep — you can set per-key colors.",
      date: "Apr 2, 2025",
    },
    {
      id: "e2-r2",
      name: "Riley J.",
      rating: 5,
      title: "Build quality is outstanding",
      body: "The aluminum frame feels premium and has zero flex. Keycaps are PBT doubleshot so they won't shine over time. I type around 80 WPM and this board keeps up flawlessly. The detachable USB-C cable is a nice touch.",
      date: "Mar 18, 2025",
    },
    {
      id: "e2-r3",
      name: "Casey N.",
      rating: 4,
      title: "Great keyboard, wish it had a numpad",
      body: "For coding and gaming this TKL layout is fantastic — more mouse room is a real benefit. But I do a lot of spreadsheet work and I miss having a numpad. The keyboard itself is flawless though.",
      date: "Feb 9, 2025",
    },
  ],

  e3: [
    {
      id: "e3-r1",
      name: "Taylor W.",
      rating: 4,
      title: "Essential for MacBook users",
      body: "Plugged it into my M2 MacBook and everything just worked. HDMI output at 4K, SD card reads at full speed, and the passthrough charging doesn't get warm. Compact enough to toss in my bag daily.",
      date: "Mar 25, 2025",
    },
    {
      id: "e3-r2",
      name: "Dana R.",
      rating: 5,
      title: "Finally, a hub that doesn't overheat",
      body: "I've gone through three USB-C hubs before this one. All of them would get scorching hot during extended use. This one stays cool even when I'm running an external monitor, charging, and transferring files simultaneously.",
      date: "Feb 14, 2025",
    },
    {
      id: "e3-r3",
      name: "Quinn B.",
      rating: 4,
      title: "Does what it says",
      body: "No frills, no driver issues, no flickering displays. It's a USB-C hub that works reliably. The braided cable feels durable and the ports have good grip. Only wish it had an ethernet port too.",
      date: "Jan 30, 2025",
    },
    {
      id: "e3-r4",
      name: "Morgan P.",
      rating: 4,
      title: "Good value for a 7-in-1",
      body: "At this price point you're getting a lot of connectivity. USB-A ports transfer at decent speeds, HDMI output is crisp, and the SD card slot saved me from carrying a separate reader. Solid buy.",
      date: "Dec 20, 2024",
    },
  ],

  e4: [
    {
      id: "e4-r1",
      name: "Nadia K.",
      rating: 4,
      title: "Perfect for pool parties",
      body: "Took this to a pool party and it survived being splashed repeatedly. Sound is surprisingly full for its size — not audiophile quality, but more than good enough outdoors. Battery lasted the entire afternoon.",
      date: "Apr 8, 2025",
    },
    {
      id: "e4-r2",
      name: "Chris H.",
      rating: 4,
      title: "Compact with decent bass",
      body: "The 360-degree sound claim is legit — sounds good from any direction. Bass is punchy without distortion at high volumes. It's small enough to clip onto a backpack which is great for hikes.",
      date: "Mar 1, 2025",
    },
    {
      id: "e4-r3",
      name: "Jordan K.",
      rating: 5,
      title: "My third one — buying them as gifts now",
      body: "I liked my first one so much I bought two more as gifts. The waterproofing is legit (tested in the shower), Bluetooth range is about 30 feet through walls, and the battery consistently lasts 11-12 hours.",
      date: "Feb 10, 2025",
    },
  ],

  // ── Books ─────────────────────────────────────────────────
  b1: [
    {
      id: "b1-r1",
      name: "Arjun D.",
      rating: 5,
      title: "Changed how I write code",
      body: "Every developer should read this before their third year of professional work. The chapter on meaningful names alone improved my code reviews dramatically. I keep it on my desk and reference it regularly.",
      date: "Mar 20, 2025",
    },
    {
      id: "b1-r2",
      name: "Emily V.",
      rating: 5,
      title: "Timeless software craftsmanship",
      body: "Even though some examples are in Java, the principles are universal. The sections on functions and error handling are worth the price alone. My team adopted Uncle Bob's rules and our codebase is noticeably cleaner.",
      date: "Feb 5, 2025",
    },
    {
      id: "b1-r3",
      name: "Sam P.",
      rating: 4,
      title: "Essential but slightly dated",
      body: "The core message about writing readable, maintainable code is as relevant as ever. Some of the specific patterns feel a bit Java-centric and pre-functional-programming, but 90% of the advice applies to any language.",
      date: "Jan 12, 2025",
    },
    {
      id: "b1-r4",
      name: "Lena W.",
      rating: 5,
      title: "Re-read it every year",
      body: "This is one of those books that reveals new insights each time you read it. As my experience grows, different chapters resonate. The chapter on unit tests is particularly good — transformed my testing approach entirely.",
      date: "Dec 1, 2024",
    },
  ],

  b2: [
    {
      id: "b2-r1",
      name: "Morgan R.",
      rating: 5,
      title: "Pure fantasy nostalgia",
      body: "This book brought me back to the golden age of fantasy. The world-building is rich, the characters are memorable, and the pacing keeps you turning pages. If you loved classic D&D-style fantasy, this is a must-read.",
      date: "Apr 5, 2025",
    },
    {
      id: "b2-r2",
      name: "Will C.",
      rating: 4,
      title: "Great start to the series",
      body: "Dragonfall sets up the world beautifully. Tanis Half-Elven is a compelling protagonist and the ensemble cast each has distinct motivations. A few pacing issues in the middle but the finale more than makes up for it.",
      date: "Mar 3, 2025",
    },
    {
      id: "b2-r3",
      name: "Casey L.",
      rating: 5,
      title: "Couldn't put it down",
      body: "Read this in two sittings. The dragon encounters are genuinely thrilling and the friendships between the companions feel authentic. Already ordered the next book in the series.",
      date: "Jan 28, 2025",
    },
  ],

  b3: [
    {
      id: "b3-r1",
      name: "Dev P.",
      rating: 5,
      title: "Finally understand closures and scope",
      body: "After years of writing JavaScript, this book made me realize how much I was just guessing. The explanation of closures, prototypes, and the event loop finally clicked. Kyle Simpson has a gift for making complex topics accessible.",
      date: "Mar 28, 2025",
    },
    {
      id: "b3-r2",
      name: "Hannah M.",
      rating: 4,
      title: "Dense but rewarding",
      body: "This isn't a casual read — you need to engage with the examples and really think. But if you put in the effort, you'll come out understanding JavaScript at a fundamentally deeper level. The 'this' chapter alone is worth it.",
      date: "Feb 22, 2025",
    },
    {
      id: "b3-r3",
      name: "Riley J.",
      rating: 5,
      title: "Should be required reading",
      body: "Every JavaScript developer should read this series. I thought I knew JS well after five years of professional work — turns out I was barely scratching the surface. The async patterns section is outstanding.",
      date: "Jan 5, 2025",
    },
    {
      id: "b3-r4",
      name: "Alex M.",
      rating: 4,
      title: "Great depth, occasionally academic",
      body: "The deep dives into language mechanics are unmatched. Occasionally it gets a bit too academic and theoretical, but those sections are still valuable for understanding why JavaScript behaves the way it does.",
      date: "Nov 18, 2024",
    },
  ],

  b4: [
    {
      id: "b4-r1",
      name: "Finn O.",
      rating: 5,
      title: "The book that started it all",
      body: "Even after the TV show, reading this for the first time was incredible. The depth of the political intrigue, the moral complexity of every character, and Martin's ability to subvert expectations — it's a masterwork of fantasy.",
      date: "Apr 10, 2025",
    },
    {
      id: "b4-r2",
      name: "Taylor W.",
      rating: 5,
      title: "Dense, brutal, and utterly gripping",
      body: "This is not a fast read. It demands attention and rewards it tenfold. Every chapter ending makes you want to keep going. The POV structure gives you perspective on every side of the conflict. A modern classic.",
      date: "Mar 15, 2025",
    },
    {
      id: "b4-r3",
      name: "Zara A.",
      rating: 5,
      title: "Better than the show by miles",
      body: "I watched the show first and the book adds so much depth. Internal monologues, subtle foreshadowing, and entire subplots that were cut from the adaptation. If you only know the story from TV, you're missing out.",
      date: "Feb 1, 2025",
    },
    {
      id: "b4-r4",
      name: "Quinn B.",
      rating: 4,
      title: "Incredible world-building",
      body: "The world of Westeros feels lived-in and real. Martin's attention to history, heraldry, and food descriptions (yes, the food) create an immersive experience. Takes about 100 pages to get into but then it's unputdownable.",
      date: "Dec 15, 2024",
    },
  ],

  // ── Clothing ──────────────────────────────────────────────
  c1: [
    {
      id: "c1-r1",
      name: "Nina G.",
      rating: 4,
      title: "Exactly what a white tee should be",
      body: "Not too thick, not too thin. The cotton is soft and it held up after 10+ washes without losing shape. The fit is true to size — I ordered my usual medium and it's perfect. A solid everyday staple.",
      date: "Apr 1, 2025",
    },
    {
      id: "c1-r2",
      name: "Marcus L.",
      rating: 4,
      title: "Great basics, ordered three more",
      body: "At this price for the quality you get, it's a no-brainer. Slightly thicker than fast-fashion tees which means it drapes better and isn't see-through. The crew neck sits well without being too tight.",
      date: "Mar 10, 2025",
    },
    {
      id: "c1-r3",
      name: "Ava R.",
      rating: 4,
      title: "Simple and reliable",
      body: "Nothing flashy, just a well-made white t-shirt. The pre-shrunk claim is accurate — same fit after washing. I sized up for an oversized look and it works great tucked or untucked. Good quality cotton.",
      date: "Feb 15, 2025",
    },
  ],

  c2: [
    {
      id: "c2-r1",
      name: "Jake F.",
      rating: 5,
      title: "Genuinely keeps you dry",
      body: "I sweat a lot during workouts and this shirt handles it like a champ. After an hour of HIIT I'm drenched, but the fabric doesn't cling or feel heavy. Dries incredibly fast too — almost dry by the time I drive home.",
      date: "Mar 22, 2025",
    },
    {
      id: "c2-r2",
      name: "Priya S.",
      rating: 4,
      title: "Great gym shirt, runs slightly large",
      body: "Love the moisture-wicking fabric for both gym and running. My only note is it runs a half-size large compared to regular Nike tees. I'd recommend sizing down if you prefer a fitted look.",
      date: "Feb 28, 2025",
    },
    {
      id: "c2-r3",
      name: "Chris H.",
      rating: 4,
      title: "My go-to workout shirt",
      body: "I own four of these in different colors now. They wash well, don't develop odor like some synthetics, and the fit allows full range of motion. Worth the premium over generic athletic tees.",
      date: "Jan 20, 2025",
    },
    {
      id: "c2-r4",
      name: "Sam P.",
      rating: 4,
      title: "Comfortable for all-day wear",
      body: "I wear this for workouts but also for casual weekend wear. It's lightweight enough for summer heat and the Dri-FIT fabric keeps you feeling fresh. The black color hasn't faded after months of washing.",
      date: "Dec 8, 2024",
    },
  ],

  c3: [
    {
      id: "c3-r1",
      name: "Jordan K.",
      rating: 5,
      title: "Heaviest, coziest hoodie I own",
      body: "This thing is a tank. The fleece inside is thick and plush, the YKK zipper glides smoothly, and the kangaroo pocket is deep enough to actually hold things. Perfect for fall and winter layering.",
      date: "Apr 3, 2025",
    },
    {
      id: "c3-r2",
      name: "Lena W.",
      rating: 4,
      title: "Premium feel, runs warm",
      body: "The quality is immediately obvious when you pick it up — it has real weight to it. The hood stays up without drawstrings digging in. Just note it runs warm, so it's more of a cold-weather piece than a light layer.",
      date: "Mar 5, 2025",
    },
    {
      id: "c3-r3",
      name: "Will C.",
      rating: 4,
      title: "Solid construction, love the fit",
      body: "After three months of regular wear and washing, it looks brand new. No pilling, no stretched cuffs, no zipper issues. The slightly oversized fit is trendy and comfortable. Would buy in more colors.",
      date: "Feb 12, 2025",
    },
  ],

  c4: [
    {
      id: "c4-r1",
      name: "Emily V.",
      rating: 5,
      title: "My feet actually feel good after 5 miles",
      body: "I've tried a dozen running shoes and these are the first that don't leave my feet aching after a long run. The foam sole absorbs impact beautifully and the mesh keeps airflow going. Genuinely impressed.",
      date: "Mar 30, 2025",
    },
    {
      id: "c4-r2",
      name: "Arjun D.",
      rating: 4,
      title: "Lightweight and responsive",
      body: "These feel like wearing socks with soles. The mesh upper is incredibly breathable — almost too breathable for winter runs. The responsive foam gives great energy return. True to size with running socks.",
      date: "Feb 18, 2025",
    },
    {
      id: "c4-r3",
      name: "Dana R.",
      rating: 5,
      title: "Perfect daily trainers",
      body: "I use these for daily 3-5 mile runs and they've held up great over 200+ miles. The outsole grip is solid on both wet and dry pavement. At this price, they outperform shoes that cost twice as much.",
      date: "Jan 10, 2025",
    },
    {
      id: "c4-r4",
      name: "Nadia K.",
      rating: 4,
      title: "Comfortable and stylish",
      body: "Not just great for running — they look good enough to wear casually. The colorway is versatile and the silhouette is sleek. Arch support could be slightly better but insoles solve that easily.",
      date: "Dec 22, 2024",
    },
  ],
};

export default reviewsByProductId;
